# options for opal-rails
# spec_url: The url to hit to run the specs. You may want it to hit your rails_app/opal_spec
# sound_on:  defaults to true set to false to turn off, works w/osx terminal-notifier
# success_sound: Sound played with successful specs, defaults to "default", I use a custom applause sound
# fail_sound: Sound played with failed specs, defaults to "Sosumi"
guard "opal-rails", :spec_url => "http://accounts.hedgeye.dev/opal_spec" do
  # include where opal files and opal specs live, below are the defaults for
  # opal-rails 0.7.1+
  watch Regexp.new("(app/assets/javascripts|spec-opal)/.+\.rb")
end
